apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: skcserviceuniquelabel123
  labels:
    app: skc-app-1
  name: skc-svc-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: skc-app-1
