trigger:
- master

resources:
- repo: self

# variables:
# - group: my-variable-grp-1
# - name: image-Build-BuildId

stages:
  - stage: Deploy
    displayName: Deploy image
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo "Hello world-$(image-Build-BuildId)"
      # - task: DownloadPipelineArtifact@2
      #   displayName: Download Artifact - configs
      #   inputs:
      #     buildType: 'specific'
      #     project: '31f3e923-2650-42ab-ad4c-9b253d18ad45'
      #     definition: '3'
      #     buildVersionToDownload: 'latest'
      #     artifactName: 'artifact-4-k8-deploy'
      #     itemPattern: '**/*.yaml'
      #     targetPath: '$(System.ArtifactsDirectory)'
      # - task: KubernetesManifest@0
      #   displayName: Deploy to AKS
      #   inputs:
      #     action: 'deploy'
      #     kubernetesServiceConnection: 'az-k8-cluster-svc-connection'
      #     namespace: 'default'
      #     manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
      #     containers: 'myreposayankc/skcnginx'